name: Upload Python Package

on:
  release:
    

jobs:
  deploy:
    
    # By using an environment, a maintainer has to approve it first
    environment: deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          
      - name: Install dependencies with Poetry
        run: python3 -m poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      
      - name: Install dasel
        run: |
          curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
          mv ./dasel /usr/local/bin/dasel
          
      - name: Get current package version
        run: dasel select -f pyproject.toml version
